config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    get 'control'
    get 'consultation'


    post 'control'
    post 'consultation'

    post 'year_report'
    post 'month_report'

    get 'detailed_control'
    post 'detailed_control'

  end

  namespace :planification do
    #TODO: Adjust request type 
    get 'monthly'
    post 'monthly'

    get 'change_version_monthly'
    get 'change_analysis_version_name'
    get 'new_monthly_budget_modal'

    post 'new_monthly_budget_version'

    get 'open_adjustments_form_modal'
    get 'open_base_adjustments_modal'
    post 'create_budget_base'
    post 'new_monthly_base'
    get 'process_quater_details'
    get 'control_report'

    get 'adjust_monthly_base'
    patch 'process_base_adjustment'

    post 'new_item_adjustment'
    post 'delete_item_adjustment'
    get 'change_base_type'
    get 'change_adjustment_amount'
  end

  namespace :annual_planification do

    get 'new_annual_planification' 
    get 'planification' #Load the initial information
    get 'annual_budget_details' # Process all selects changes (year,month,version)

    post 'create_annual_version' # Process the modal of new annual_version

    get 'load_base' #load the information to update a given base
    get 'change_base_type' #LOAD the info about the base type
    patch 'adjust_base' # Update the base for a given item and subfield

    get 'load_adjustments' #Load the information to create or update new adjustments
    post 'process_adjustments' # Update exiting adjustments or create new ones
    get 'add_virtual_adjustment' # add new row in virtual adjustment form

    get 'change_adjustment_amount' #load the information of percentaje in virtual_adjustment

    get 'quater_details'

    get 'control_report' #Load the information for the table control report
  end

  resources :adjustments do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end

  resources :estimates do
   collection {post :import}
   collection {get :excel_example}
  end

  resources :budgets do
    collection { post :import }
    collection { get :check_year }
    collection {get :excel_example}
    collection { get :source }
  end
  resources :transactions do
    collection { get :bank_excel_example }
    collection { get :filial_excel_example }
    collection { post :import }
    collection {get :all, defaults: { format: :json}}
    collection { get :source }
  end
  resources :users do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end
  resources :accounts do
    collection{post :import}
    collection{get :excel_example}
    collection { get :source }
  end
  resources :items do
    collection { post :import }
    collection { get :excel_example }
    collection { get :source }
  end
  resources :cost_centers do
    collection { post :import }
    collection { get :import_excel_example }
    collection { get :source }
  end
  resources :month_planifications do
    collection {post :create}
  end
  resources :base_adjustments
  resources :theoric_adjustments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
end

app/models/estimate.rb
# == Schema Information
#
# Table name: estimates
#
#  id             :integer          not null, primary key
#  estimates_type :string
#  name           :string
#  amount         :float
#  date           :date
#  item_id        :integer
#  account_id     :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class Estimate < ApplicationRecord
  belongs_to :item
  belongs_to :account
  validates_presence_of :name,
                        :amount,
                        :date
  validates :amount, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only:[:show, :edit, :update, :destroy]
  before_action :load_internationalization, only:[:index,:import]
  before_action :set_estimates, only:[:import]

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimación creada.' }
        format.json { render :show, status: :created, location: @estimate }
      else
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimación actualizada.' }
        format.json { render :show, status: :ok, location: @estimate }
      else
        format.html { render :edit }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to estimates_url, notice: 'Estimación eliminada.' }
      format.json { head :no_content }
    end
  end

  def excel_example
    send_file Rails.root.join('public','ejemplo_estimaciones.xlsx').to_s, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end

  def import
    if params[:file]
      row_param = ExcelReader::RowEstimate.read_spreadsheet(params[:file])
      if row_param.is_a?(ExcelReader::Row)
        @row_with_error = row_param
        render 'index'
      else
        row_with_error = row_param.row_with_error
        if row_with_error.is_a?(ExcelReader::Row)
          @row_with_error = row_with_error
          render 'index'
        else
          flash[:notice] = "Se han agregado #{row_param.news_counter}  y se han editado #{row_param.edits_counter} ajustes correctamente."
          redirect_to estimates_path
        end
      end
    else
      redirect_to estimates_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    def set_estimates
      @estimates = Estimate.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:item_id, :account_id, :amount, :estimates_type,:date, :name)
    end

    def load_internationalization
      @estimate_t = t('activerecord.models.estimate')
      @estimate_attributes_t = t('activerecord.attributes.estimate')
      @actions_t = t('actions')
    end


end

app/views/estimates/_form.html.haml
= form_for @estimate, html: { class: "form-horizontal", role: "form" } do |f|
  -if @estimate.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close

      %h4= "#{pluralize(@estimate.errors.count, "error")} prohibido que esta estimación se guarde:"

      %ul
        - @estimate.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :item, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :item, class: 'form-control'
  .form-group
    = f.label :account, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :account, class: 'form-control'
  .form-group
    = f.label :amount, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :amount, class: 'form-control'
  .form-group
    = f.label :estimate_type, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :estimates_type, class: 'form-control'
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :date, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :date, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/estimates/edit.html.haml
.page-header
  = link_to estimates_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt

    Atrás

  = link_to @estimate, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editar Estimaciones

= render 'form'

app/views/estimates/index.html.haml
.row
  .col-md-12
    %h1 Importar Estimaciones
    = form_tag import_estimates_path, multipart: true, class:'form-horizontal' do
      - unless @row_with_error.nil?
        = bootstrap_model_errors(@row_with_error, "Error en fila #{@row_with_error.row_number} del archivo excel:")

      .form-group
        %label.control-label.col-sm-2{:for => "file"} Archivo Excel:
        .col-sm-10
          = file_field_tag :file, class:'form-control'


      .form-group
        .col-sm-offset-2.col-sm-10
          = link_to 'Descargar excel ejemplo estimaciones',excel_example_estimates_path(format: "xlsx"), class: 'btn btn-default'
      .form-group
        .col-sm-offset-2.col-sm-10
          = submit_tag "Subir archivo", class:'btn btn-danger'

.page-header
  = link_to new_estimate_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    = "#{@actions_t[:new]} #{@estimate_t[:one]}"
  %h1
    = "#{@estimate_t[:other]}"

.table-responsive
  %table.table.table-striped.table-bordered.table-hover.table-initialization
    %thead
      %tr
        %th
          Concepto
        %th
          Tipo
        %th
          Monto
        %th
          Fecha
        %th
          Item
        %th
          Cuenta

    %tbody
      - @estimates.each do |estimate|
        %tr
          %td= link_to estimate.name, estimate
          %td= estimate.estimates_type
          %td= currency_format(estimate.amount)
          %td= document_date_format(estimate.date)
          %td= estimate.item.description if estimate.item.present?
          %td= estimate.account.name if estimate.account.present?

          %td=(link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_estimate_path(estimate))+"  "+(link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, estimate, data: { confirm: '¿Estás seguro?' }, method: :delete)

app/views/estimates/new.html.haml
.page-header
  = link_to estimates_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás

  %h1 Nuevo estimación

= render 'form'

app/views/estimates/show.html.haml
.page-header
  = link_to adjustments_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás

  = link_to edit_adjustment_path(@estimate), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Editar

  %h1="Transacción #{@estimate.name}"

%dl.dl-horizontal

  %dt Nombre:
  %dd= @estimate.name
  %dt Nombre Cuenta:
  %dd= @estimate.account.present? ? @estimate.account.name : ""
  %dt Nombre Item:
  %dd= @estimate.item.present? ? @estimate.item.description : ""
  %dt Monto transacción:
  %dd= currency_format(@estimate.amount)
  %dt Tipo:
  %dd= @estimate.estimates_type