config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    get 'control'
    get 'consultation'


    post 'control'
    post 'consultation'

    post 'year_report'
    post 'month_report'

    get 'detailed_control'
    post 'detailed_control'

  end

  namespace :planification do
    #TODO: Adjust request type 
    get 'monthly'
    post 'monthly'

    get 'change_version_monthly'
    get 'change_analysis_version_name'
    get 'new_monthly_budget_modal'

    post 'new_monthly_budget_version'

    get 'open_adjustments_form_modal'
    get 'open_base_adjustments_modal'
    post 'create_budget_base'
    post 'new_monthly_base'
    get 'process_quater_details'
    get 'control_report'

    get 'adjust_monthly_base'
    patch 'process_base_adjustment'

    post 'new_item_adjustment'
    post 'delete_item_adjustment'
    get 'change_base_type'
    get 'change_adjustment_amount'
  end

  namespace :annual_planification do

    get 'new_annual_planification' 
    get 'planification' #Load the initial information
    get 'annual_budget_details' # Process all selects changes (year,month,version)

    post 'create_annual_version' # Process the modal of new annual_version

    get 'load_base' #load the information to update a given base
    get 'change_base_type' #LOAD the info about the base type
    patch 'adjust_base' # Update the base for a given item and subfield

    get 'load_adjustments' #Load the information to create or update new adjustments
    post 'process_adjustments' # Update exiting adjustments or create new ones
    get 'add_virtual_adjustment' # add new row in virtual adjustment form

    get 'change_adjustment_amount' #load the information of percentaje in virtual_adjustment

    get 'quater_details'

    get 'control_report' #Load the information for the table control report
  end

  resources :adjustments do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end

  resources :estimates do
   collection {post :import}
   collection {get :excel_example}
  end

  resources :budgets do
    collection { post :import }
    collection { get :check_year }
    collection {get :excel_example}
    collection { get :source }
  end
  resources :transactions do
    collection { get :bank_excel_example }
    collection { get :filial_excel_example }
    collection { post :import }
    collection {get :all, defaults: { format: :json}}
    collection { get :source }
  end
  resources :users do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end
  resources :accounts do
    collection{post :import}
    collection{get :excel_example}
    collection { get :source }
  end
  resources :items do
    collection { post :import }
    collection { get :excel_example }
    collection { get :source }
  end
  resources :cost_centers do
    collection { post :import }
    collection { get :import_excel_example }
    collection { get :source }
  end
  resources :month_planifications do
    collection {post :create}
  end
  resources :base_adjustments
  resources :theoric_adjustments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
end

app/models/cost_center.rb
# == Schema Information
#
# Table name: cost_centers
#
#  id          :integer          not null, primary key
#  code        :string
#  name        :string
#  division    :string
#  area        :string
#  subarea     :string
#  created_at  :datetime
#  updated_at  :datetime
#  description :string
#  management  :string
#

class CostCenter < ApplicationRecord

  include ActionView::Helpers
  include ActionView::Context
  include Rails.application.routes.url_helpers
  include CostCentersHelper

  has_many :transactions, dependent: :delete_all

  validates_presence_of :code,
                      :name

  scope :by_division, ->(cost_centers,division) {cost_centers.where(division: division)}
  scope :by_management, ->(cost_centers,management) {cost_centers.where(management: management)}
  scope :by_area, ->(cost_centers,area) {cost_centers.where(area: area)}
  scope :by_subarea, ->(cost_centers,subarea) {cost_centers.where(subarea: subarea)}

  validate  :validate_uniq_code,
            :validate_uniq_code_name,
            :validate_uniq_code_name_description,
            :validate_uniq_code_name_description_management,
            :validate_uniq_code_name_description_management_division,
            :validate_uniq_code_name_description_management_division_area,
            :validate_uniq_code_name_description_management_division_area_subarea

  def validate_uniq_code
    result = CostCenter.where(code:self.code).where(name:[nil, ""]).where(description: [nil, ""]).where(management: [nil, ""]).where(division: [nil, ""]).where(area: [nil, ""]).where(subarea: [nil, ""]).first

    if result.present?
      self.errors.add(:base,"El código #{self.code} ya está siendo utilizado.")
    end
  end

  def validate_uniq_code_name
    result = CostCenter.where(code:self.code).where(name:self.name).where(description: [nil, ""]).where(management: [nil, ""]).where(division: [nil, ""]).where(area: [nil, ""]).where(subarea: [nil, ""]).first
    if result.present?
      self.errors.add(:base,"El código #{self.code} y el nombre #{self.name} ya están siendo utilizados.")
    end
  end

  def validate_uniq_code_name_description
    result = CostCenter.where(code:self.code).where(name:self.name).where(description: self.description).where(management: [nil, ""]).where(division: [nil, ""]).where(area: [nil, ""]).where(subarea: [nil, ""]).first
    if result.present?
      self.errors.add(:base,"El código #{self.code}, el nombre #{self.name} y la descripción #{self.description} ya están siendo utilizados.")
    end
  end

  def validate_uniq_code_name_description_management
    CostCenter.where(code:self.code).where(name:self.name).where(description: self.description).where(management: self.management).where(division: [nil, ""]).where(area: [nil, ""]).where(subarea: [nil, ""]).first
  end

  def validate_uniq_code_name_description_management_division
    CostCenter.where(code:self.code).where(name:self.name).where(description: self.description).where(management: self.management).where(division: self.division).where(area: [nil, ""]).where(subarea: [nil, ""]).first
  end

  def validate_uniq_code_name_description_management_division_area
    CostCenter.where(code:self.code).where(name:self.name).where(description: self.description).where(management: self.management).where(division: self.division).where(area: self.area).where(subarea: [nil, ""]).first
  end

  def validate_uniq_code_name_description_management_division_area_subarea
    CostCenter.where(code:self.code).where(name:self.name).where(description: self.description).where(management: self.management).where(division: self.division).where(area: self.area).where(subarea: self.subarea).first
  end

  def self.division_availables
    CostCenter.pluck(:division)
  end
  def self.management_availables
    CostCenter.pluck(:management)
  end
  def self.area_availables
    CostCenter.pluck(:area)
  end
  def self.subarea_availables
    CostCenter.pluck(:subarea)
  end

  def actions
    actions_links(self)
  end
end

app/controllers/cost_centers_controller.rb
class CostCentersController < ApplicationController
  before_action :set_cost_center, only: [:show, :edit, :update, :destroy]
  before_action :set_cost_centers, only: [:import]
  # GET /cost_centers
  # GET /cost_centers.json
  def index
    @cost_centers = CostCenter.all
  end

  # GET /cost_centers/1
  # GET /cost_centers/1.json
  def show

  end

  # GET /cost_centers/new
  def new
    @cost_center = CostCenter.new
  end

  # GET /cost_centers/1/edit
  def edit
  end

  # POST /cost_centers
  # POST /cost_centers.json
  def create
    @cost_center = CostCenter.new(cost_center_params)

    respond_to do |format|
      if @cost_center.save
        format.html { redirect_to @cost_center, notice: 'Centro de costo creado.' }
        format.json { render :show, status: :created, location: @cost_center }
      else
        format.html { render :new }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cost_centers/1
  # PATCH/PUT /cost_centers/1.json
  def update
    respond_to do |format|
      if @cost_center.update(cost_center_params)
        format.html { redirect_to @cost_center, notice: 'Centro de costo actualizado.' }
        format.json { render :show, status: :ok, location: @cost_center }
      else
        format.html { render :edit }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_centers/1
  # DELETE /cost_centers/1.json
  def destroy
    @cost_center.destroy
    respond_to do |format|
      format.html { redirect_to cost_centers_url, notice: 'Centro de costo eliminado.' }
      format.json { head :no_content }
    end
  end

  def import_excel_example
      send_file Rails.root.join('public','ejemplo_centro_costo.xlsx').to_s, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end

  def import
    #TODO: Refactor this code.
    if params[:file]
      row_param = ExcelReader::RowCostCenter.read_spreadsheet(params[:file])

      if row_param.is_a?(ExcelReader::Row)
        @row_with_error = row_param
        render 'index'
      else
        row_with_error = row_param.row_with_error
        if row_with_error.is_a?(ExcelReader::Row)
          @row_with_error = row_with_error
          render 'index'
        else
          flash[:notice] = "Se han agregado #{row_param.news_counter} centros de costos correctamente."
          redirect_to cost_centers_path
        end
      end
    else
      redirect_to cost_centers_path
    end
  end

  def source
    respond_to do |format|
      format.html
      format.json { render json: CostCenterDatatable.new(view_context) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_center
      @cost_center = CostCenter.find(params[:id])
    end

    def set_cost_centers
      @cost_centers = CostCenter.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_center_params
      params.require(:cost_center).permit(:code,:name,:division,:area,:subarea,:description,:management)
    end
end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
  def load_index_translations
    @cost_center_t = t('activerecord.models.cost_center')
    @cost_center_attributes_t = t('activerecord.attributes.cost_center')
    @actions_t = t('actions')
  end

  def edit_object_link(object,icon)
    link_to content_tag(:span,"",class:"glyphicon #{icon.to_s}"), edit_cost_center_path(object)
  end

  def delete_object_link(object,icon)
    link_to content_tag(:span,"",class:"glyphicon #{icon.to_s}"),object, data: { confirm: '¿Estás seguro?' }, method: :delete
  end

  def actions_links(object)
    edit_object_link(object,"glyphicon-pencil") + delete_object_link(object,"glyphicon-remove")
  end
end

app/views/cost_centers/_cost_centers_table.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover#cost-centers-table{ "data-source" => "#{source_cost_centers_path(format: :json)}"}
    %thead
      %tr
        %th Código
        %th Nombre
        %th División
        %th Gerencia
        %th Área
        %th Subarea
        %th Acciones
    %tbody

app/views/cost_centers/_form.html.haml
= form_for @cost_center, html: { class: "form-horizontal", role: "form" } do |f|
  -if @cost_center.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@cost_center.errors.count, "error")} prohibido que este centro de costo se guarde:"

      %ul
        - @cost_center.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :code, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :code, class: 'form-control'
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :descripcion, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :division, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :division, class: 'form-control'
  .form-group
    = f.label :gerencia, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :management, class: 'form-control'
  .form-group
    = f.label :area, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :area, class: 'form-control'
  .form-group
    = f.label :subarea, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :subarea, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/cost_centers/edit.html.haml
.page-header
  = link_to cost_centers_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás
  = link_to @cost_center, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editar centro de costos

= render 'form'

app/views/cost_centers/index.html.haml
- load_index_translations
.row
  .col-md-12
    %h1 Importar Centros de Costo
    = form_tag import_cost_centers_path, multipart: true, class:'form-horizontal' do
      - unless @row_with_error.nil?
        = bootstrap_model_errors(@row_with_error, "Error en fila #{@row_with_error.row_number} del archivo excel:")

      .form-group
        %label.control-label.col-sm-2{:for => "file"} Archivo Excel:
        .col-sm-10
          = file_field_tag :file, class:'form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = submit_tag "Subir archivos de costos", class:'btn btn-danger'
          = link_to 'Descargar ejemplo',import_excel_example_cost_centers_path(format: "xlsx"), class: 'btn btn-default'

.page-header
  = link_to new_cost_center_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    = "#{@actions_t[:new]} centro de costo"
  %h1
    Centro de Costos

= render partial: "cost_centers_table"

app/views/cost_centers/new.html.haml
.page-header
  = link_to cost_centers_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás
  %h1 Nuevo centro de costo

= render 'form'

app/views/cost_centers/show.html.haml
.page-header
  = link_to cost_centers_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás
  = link_to edit_cost_center_path(@cost_center), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Editar
  %h1 Centro de Costo

%dl.dl-horizontal
  %dt Codigo:
  %dd= @cost_center.code
  %dt Nombre:
  %dd= @cost_center.name
  %dt Descripción:
  %dd= @cost_center.description
  %dt División:
  %dd= @cost_center.division
  %dt Gerencia:
  %dd= @cost_center.management
  %dt Área
  %dd= @cost_center.area
  %dt Subarea:
  %dd= @cost_center.subarea