config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    get 'control'
    get 'consultation'


    post 'control'
    post 'consultation'

    post 'year_report'
    post 'month_report'

    get 'detailed_control'
    post 'detailed_control'

  end

  namespace :planification do
    #TODO: Adjust request type 
    get 'monthly'
    post 'monthly'

    get 'change_version_monthly'
    get 'change_analysis_version_name'
    get 'new_monthly_budget_modal'

    post 'new_monthly_budget_version'

    get 'open_adjustments_form_modal'
    get 'open_base_adjustments_modal'
    post 'create_budget_base'
    post 'new_monthly_base'
    get 'process_quater_details'
    get 'control_report'

    get 'adjust_monthly_base'
    patch 'process_base_adjustment'

    post 'new_item_adjustment'
    post 'delete_item_adjustment'
    get 'change_base_type'
    get 'change_adjustment_amount'
  end

  namespace :annual_planification do

    get 'new_annual_planification' 
    get 'planification' #Load the initial information
    get 'annual_budget_details' # Process all selects changes (year,month,version)

    post 'create_annual_version' # Process the modal of new annual_version

    get 'load_base' #load the information to update a given base
    get 'change_base_type' #LOAD the info about the base type
    patch 'adjust_base' # Update the base for a given item and subfield

    get 'load_adjustments' #Load the information to create or update new adjustments
    post 'process_adjustments' # Update exiting adjustments or create new ones
    get 'add_virtual_adjustment' # add new row in virtual adjustment form

    get 'change_adjustment_amount' #load the information of percentaje in virtual_adjustment

    get 'quater_details'

    get 'control_report' #Load the information for the table control report
  end

  resources :adjustments do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end

  resources :estimates do
   collection {post :import}
   collection {get :excel_example}
  end

  resources :budgets do
    collection { post :import }
    collection { get :check_year }
    collection {get :excel_example}
    collection { get :source }
  end
  resources :transactions do
    collection { get :bank_excel_example }
    collection { get :filial_excel_example }
    collection { post :import }
    collection {get :all, defaults: { format: :json}}
    collection { get :source }
  end
  resources :users do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end
  resources :accounts do
    collection{post :import}
    collection{get :excel_example}
    collection { get :source }
  end
  resources :items do
    collection { post :import }
    collection { get :excel_example }
    collection { get :source }
  end
  resources :cost_centers do
    collection { post :import }
    collection { get :import_excel_example }
    collection { get :source }
  end
  resources :month_planifications do
    collection {post :create}
  end
  resources :base_adjustments
  resources :theoric_adjustments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only:[:show, :edit, :update, :destroy]
  before_action :load_internationalization, only:[:index,:import]
  before_action :set_transactions, only:[:import]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.includes(account:[:item]).includes(:cost_center).page(params[:page])
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transacción creada.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transacción actualizada.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transacción eliminada.' }
      format.json { head :no_content }
    end
  end

  def bank_excel_example
    send_file Rails.root.join('public','ejemplo_banco.xlsx').to_s, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end

  def filial_excel_example
    send_file Rails.root.join('public','ejemplo_filiales.xlsx').to_s, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end

  def import

    if check_source
      flash[:error] = 'Favor especificar el tipo de origen de los datos: Banco o Filial'
      render 'index'
    else
      process_file
      if @row_param.is_a?(ExcelReader::Row)
        @row_with_error = @row_param
        render 'index'
      else
        if @row_param.row_with_error.blank? || @row_param.row_with_error.is_a?(ExcelReader::Row)
          @row_with_error = @row_param.row_with_error
          render 'index'
        else
          flash[:notice] = "Se han agregado #{@row_param.news_counter}  y se han editado #{@row_param.edits_counter} transacciones correctamente."
          redirect_to transactions_path
        end
      end
    end
  end

  def source
    respond_to do |format|
      format.html
      format.json { render json: TransactionDatatable.new(view_context) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_transactions
      @transactions = Transaction.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:item_id, :cost_center_id, :amount, :kind,:enterprise_code, :enterprise_name,:source,:account_id,:expired_date)
    end

    def load_internationalization
      @transaction_t = t('activerecord.models.transaction')
      @transaction_attributes_t = t('activerecord.attributes.transaction')
      @actions_t = t('actions')
    end

    def check_source
      !params.has_key?(:source) || !(Transaction::SOURCES.include?(params[:source]))
    end

    def process_file
      @row_param = if params[:source] == Transaction::SOURCES[0]
                ExcelReader::RowBankTransaction.read_spreadsheet(params[:file])
             elsif params[:source] == Transaction::SOURCES[1]
                ExcelReader::RowFilialTransaction.read_spreadsheet(params[:file])
             end
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def expired_date_format(expired_date)
      expired_date.present? ? expired_date.strftime("%Y-%m-%d") : '-'
  end

  def document_date_format(document_date)
      document_date.present? ? document_date.strftime("%Y-%m-%d") : '-'
  end

  def edit_object_link(object,icon)
    link_to content_tag(:span,"",class:"glyphicon #{icon.to_s}"), edit_transaction_path(object)
  end

  def delete_object_link(object,icon)
    link_to content_tag(:span,"",class:"glyphicon #{icon.to_s}"),object, data: { confirm: '¿Estás seguro?' }, method: :delete
  end

  def actions_links(object)
    edit_object_link(object,"glyphicon-pencil") + delete_object_link(object,"glyphicon-remove")
  end
  def currency_format(number)
    if number.is_a? Numeric
        number_in_millions = number/1000000.0
        number_to_currency(number_in_millions, unit: "$", precision:4,separator: ",", delimiter: ".",format: "%u %n")
    else
        '-'
    end
  end

end

app/views/transactions/_form.html.haml
= form_for @transaction, html: { class: "form-horizontal", role: "form" } do |f|
  -if @transaction.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@transaction.errors.count, "error")} prohibido que esta transacción se guarde::"

      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg



  .form-group
    = f.label :amount, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :amount, class: 'form-control'
  .form-group
    = f.label :enterprise_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :enterprise_name, class: 'form-control'
  .form-group
    = f.label :enterprise_code, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :enterprise_code, class: 'form-control'
  .form-group
    = f.label :source, class: 'col-sm-2 control-label'
    .col-sm-10.select_form
      = f.select :source, options_for_select(["Filial","Banco"],[@transaction.source])
  .form-group
    = f.label :cost_center_id, class: 'col-sm-2 control-label'
    .col-sm-10.select_form
      -cc = @transaction.cost_center
      = f.select :cost_center_id, options_for_select(CostCenter.all.map {|u| [u.name, u.id]},[cc.present? ? cc.name : nil,cc.present? ? cc.id : nil]), :include_blank => false
  .form-group
    = f.label "Cuenta", class: 'col-sm-2 control-label'
    .col-sm-10.select_form
      -account = @transaction.account
      = f.select :account_id, options_for_select(Account.all.map {|u| [u.description, u.id]},[account.present? ? account.description : nil,account.present? ? account.id : nil]), :include_blank => false
  .form-group
    = f.label :expired_date, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :expired_date, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary', :value => "Actualizar gastos"

app/views/transactions/_transactions_table.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover#transactions-table{ "data-source" => "#{source_transactions_path(format: :json)}"}
    %thead
      %tr
        %th
          Cuenta
        %th
          Item
        %th
          Centro de Costo
        %th
          Monto
        %th
          Fuente
        %th
          Fecha de Contabilización
        %th
          Fecha de Documento
        %th
          Glosa
        %th
          Codigo de empresa
        %th
          Nombre de empresa
        %th
    %tbody

app/views/transactions/edit.html.haml
.page-header
  = link_to transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás
  = link_to @transaction, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Mostrar transacción
  %h1 Editar transacción

= render 'form'

app/views/transactions/index.html.haml
.row
  .col-md-12
    %h1 Importar Gastos
    = form_tag import_transactions_path, multipart: true, class:'form-horizontal' do
      - unless @row_with_error.nil?
        = bootstrap_model_errors(@row_with_error, "Error en fila #{@row_with_error.row_number} del archivo excel:")

      .form-group
        %label.control-label.col-sm-2{:for => "file"} Archivo Excel:
        .col-sm-10
          = file_field_tag :file, class:'form-control'
      .form-group
        %label.control-label.col-sm-2{:for => "source"} Fuente
        .col-sm-10
          = radio_button_tag :source,'bank'
          Banco
          = radio_button_tag :source,'filial'
          Filial


      .form-group
        .col-sm-offset-2.col-sm-10
          = link_to 'Descargar excel ejemplo banco',bank_excel_example_transactions_path(format: "xlsx"), class: 'btn btn-default'
          = link_to 'Descargar excel ejemplo filial',filial_excel_example_transactions_path(format: "xlsx"), class: 'btn btn-default'
      .form-group
        .col-sm-offset-2.col-sm-10
          = submit_tag "Subir archivo", class:'btn btn-danger'

.page-header
  = link_to new_transaction_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    = "#{@actions_t[:new]} #{@transaction_t[:one]}"
  %h1
    = "#{@transaction_t[:other]}"

= render partial:"transactions_table"

app/views/transactions/index.js.erb
$('#container-transactions-table').empty();
$('#container-transactions-table').html('<%= escape_javascript(render "transactions/partials/transactions_table",locals: {transactions: @transactions}) %>');

$('#counter').empty();
$('#counter').html('<%= escape_javascript(paginate @transactions, :remote => true %>');

app/views/transactions/new.html.haml
.page-header
  = link_to transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Atrás
  %h1 Nueva transacción

= render 'form'

app/views/transactions/show.html.haml
.page-header
  = link_to transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    atrás
  = link_to edit_transaction_path(@transaction), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Editar
  %h1="Transacción #{@transaction.account.name}"

%dl.dl-horizontal

  %dt Nombre Item:
  %dd= @transaction.account.item.description if @transaction.account.item.present?
  %dt Codigo Item:
  %dd= @transaction.account.item.code if @transaction.account.item.present?
  %dt Nombre Centro de costo:
  %dd= @transaction.cost_center.name if @transaction.cost_center.present?
  %dt Monto transacción:
  %dd= currency_format(@transaction.amount)
  %dt Fuente:
  %dd= @transaction.source
  %dt Cuenta:
  %dd= @transaction.account.present? ? @transaction.account.description : ""
  %dt Centro de costos:
  %dd= @transaction.cost_center.present? ? @transaction.cost_center.name : ""