config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    get 'control'
    get 'consultation'


    post 'control'
    post 'consultation'

    post 'year_report'
    post 'month_report'

    get 'detailed_control'
    post 'detailed_control'

  end

  namespace :planification do
    #TODO: Adjust request type 
    get 'monthly'
    post 'monthly'

    get 'change_version_monthly'
    get 'change_analysis_version_name'
    get 'new_monthly_budget_modal'

    post 'new_monthly_budget_version'

    get 'open_adjustments_form_modal'
    get 'open_base_adjustments_modal'
    post 'create_budget_base'
    post 'new_monthly_base'
    get 'process_quater_details'
    get 'control_report'

    get 'adjust_monthly_base'
    patch 'process_base_adjustment'

    post 'new_item_adjustment'
    post 'delete_item_adjustment'
    get 'change_base_type'
    get 'change_adjustment_amount'
  end

  namespace :annual_planification do

    get 'new_annual_planification' 
    get 'planification' #Load the initial information
    get 'annual_budget_details' # Process all selects changes (year,month,version)

    post 'create_annual_version' # Process the modal of new annual_version

    get 'load_base' #load the information to update a given base
    get 'change_base_type' #LOAD the info about the base type
    patch 'adjust_base' # Update the base for a given item and subfield

    get 'load_adjustments' #Load the information to create or update new adjustments
    post 'process_adjustments' # Update exiting adjustments or create new ones
    get 'add_virtual_adjustment' # add new row in virtual adjustment form

    get 'change_adjustment_amount' #load the information of percentaje in virtual_adjustment

    get 'quater_details'

    get 'control_report' #Load the information for the table control report
  end

  resources :adjustments do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end

  resources :estimates do
   collection {post :import}
   collection {get :excel_example}
  end

  resources :budgets do
    collection { post :import }
    collection { get :check_year }
    collection {get :excel_example}
    collection { get :source }
  end
  resources :transactions do
    collection { get :bank_excel_example }
    collection { get :filial_excel_example }
    collection { post :import }
    collection {get :all, defaults: { format: :json}}
    collection { get :source }
  end
  resources :users do
    collection {post :import}
    collection {get :excel_example}
    collection { get :source }
  end
  resources :accounts do
    collection{post :import}
    collection{get :excel_example}
    collection { get :source }
  end
  resources :items do
    collection { post :import }
    collection { get :excel_example }
    collection { get :source }
  end
  resources :cost_centers do
    collection { post :import }
    collection { get :import_excel_example }
    collection { get :source }
  end
  resources :month_planifications do
    collection {post :create}
  end
  resources :base_adjustments
  resources :theoric_adjustments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
end

app/models/report.rb
class Report
    include ActiveModel::Model

    MODELS_TYPES = {format_spain: FormatSpain.name.downcase,format_ccc:InterpretationCcc.name.downcase,local_gp:InterpretationGe.name.downcase,format_cargabal:InterpretationCargabal.name.downcase,format_bank:FormatBank.name.downcase,format_group:FormatGroup.name.downcase,format_subfield:Subfield.name.downcase,division:'division',management:'management',area:'area',subarea:'subarea'}

    ANALYSIS_PERIOD = 1.year
    def self.control(options)
      #Process paramenters
      month = options[:month_report]
      year = options[:year_report]
      model_type = options[:report_type]

      #Periods
      budget = Budget.where(month:month.to_i,year:year.to_i).first
      reference_date = budget.period.to_date
      start_previous_year,end_previous_year,start_current_year,end_current_year = self.yearly_report_periods(reference_date)

      #Calculations by year
      current_year_result = self.calculations(start_current_year,end_current_year,model_type)
      previous_year_result = self.calculations(start_previous_year,end_previous_year,model_type)

      #Calculations by month
      start_date_previous_monthly,end_date_previous_monthly,start_monthly_date,end_monthly_date = self.monthly_report_periods(reference_date)
      month_current_year = self.calculations(start_monthly_date,end_monthly_date,model_type)
      month_last_year = self.calculations(start_date_previous_monthly,end_date_previous_monthly,model_type)

      #Previous Month
      start_date_previous_month = (start_monthly_date - 1.month).beginning_of_month
      end_date_previous_month = start_date_previous_month.end_of_month
      previous_month = self.calculations(start_date_previous_month,end_date_previous_month,model_type)

      #adjustment_results
      year_adjustment_result = self.adjustment_results(model_type,start_previous_year,end_previous_year,start_current_year,end_current_year)
      month_adjustment_result = self.adjustment_results(model_type,start_date_previous_monthly,end_date_previous_monthly,start_monthly_date,end_monthly_date)
      previous_month_adjustment_result = self.adjustment_results(model_type,start_date_previous_month,end_date_previous_month,nil,nil )

      OpenStruct.new(current_year_result:current_year_result,previous_year_result:previous_year_result,month_current_year:month_current_year,month_last_year:month_last_year,previous_month:previous_month,
      year_adjustment_result:year_adjustment_result,month_adjustment_result:month_adjustment_result, previous_month_adjustment_result:previous_month_adjustment_result)

    end
    def self.detailed_control_report(options)
      start_date, end_date = self.periods_for_detailed_report(options[:start_year],options[:end_year])
      model_type = options[:report_type]
      self.calculations_for_detailed_report(start_date,end_date,model_type)
    end



    def self.adjustment_results(model_type,start_date_previous_year,end_date_previous_year,start_date_current_year,end_date_current_year)
      items,table_name = self.items_by(model_type)
      results = if items.present?
                  result = self.sql_adjustment_with_item(start_date_previous_year,end_date_previous_year,start_date_current_year,end_date_current_year,items)
                else
                  result = self.sql_adjustment(start_date_previous_year,end_date_previous_year,start_date_current_year,end_date_current_year)
                end
    end

    def self.periods_for_detailed_report(start_year,end_year)
      start_date = Date.new(start_year.to_i,1,1)
      end_date = Date.new(end_year.to_i,12,31)

      return start_date,end_date
    end

    def self.yearly_report_periods(reference_date)
      end_current_year = self.set_end_current_year(reference_date)
      start_current_year = self.set_start_current_year(end_current_year)
      start_previous_year = self.set_start_previous_year(end_current_year)
      end_previous_year = self.set_end_previous_year(end_current_year)
      return start_previous_year,end_previous_year,start_current_year,end_current_year
    end

    def self.set_end_current_year(reference_date)
      actual_year = DateTime.now.year
      actual_month = DateTime.now.month
      end_current_year = if actual_year == reference_date.year and actual_month == reference_date.month
                            Date.new(reference_date.year,reference_date.month,DateTime.now.day)
                         else
                            Date.new(reference_date.year,reference_date.month,reference_date.end_of_month.day)
                         end
    end

    def self.set_start_current_year(reference_date)
      reference_date - 1.year + 1.day
    end

    def self.set_end_previous_year(reference_date)
      reference_date - 1.year
    end

    def self.set_start_previous_year(reference_date)
      reference_date - 2.year + 1.day
    end

    def self.monthly_report_periods(reference_date)
      previous_year = reference_date - 1.year
      previous_start_date = previous_year.beginning_of_month
      previous_end_date = previous_year.end_of_month
      current_start_date = reference_date.beginning_of_month
      current_end_date = reference_date.end_of_month

      return previous_start_date,previous_end_date,current_start_date,current_end_date
    end

    def self.calculations(start_date,end_date,model_type)
      items,table_name = self.items_by(model_type)

      results = if items.present?
                  result = self.sql_control_report(start_date,end_date,items.ids,table_name)
                else
                  total_transaction = Transaction.where(expired_date:start_date..end_date).sum(:amount)
                  total_budget = Budget.where(period:start_date..end_date).sum(:amount)

                  result = [OpenStruct.new(concept:'Total',transaction_result:total_transaction,budget:total_budget,item_id:'',item_code:'',item_description:'')]

                end
    end

    def self.calculations_for_detailed_report(start_date,end_date,model_type)

      items,table_name = self.items_by(model_type)

      results = if items.present?
                  self.sql_detailed_report(start_date,end_date,items,table_name)
                else
                  items = Item.all
                  self.sql_detailed_report_all_items(start_date,end_date,items)
                end
    end



    def self.items_by(model_type)
      items = nil
      table_name = nil
      if model_type == MODELS_TYPES[:format_spain]
        items = Item.format_spain
        table_name = FormatSpain.table_name
      elsif model_type == MODELS_TYPES[:format_ccc]
        items = Item.interpretation_ccc
        table_name = InterpretationCcc.table_name
      elsif model_type == MODELS_TYPES[:local_gp]
        items = Item.interpretation_ge
        table_name = InterpretationGe.table_name
      end

      return items,table_name
    end

    def self.set_consultation_dates(year)
      actual_start_date = Date.new(year,1,1)
      actual_end_date = Date.new(year,12,31)
      previous_start_date = actual_start_date - 1.year
      previous_end_date = actual_end_date - 1.year
      previous2_end_date = actual_start_date - 2.year
      previous2_start_date = actual_end_date - 2.year
      return actual_start_date,actual_end_date,previous_start_date,previous_end_date,previous2_start_date,previous2_end_date
    end

    def self.consultation(options)
      year = options[:year_report].to_i
      actual_start_date,actual_end_date,previous_start_date,previous_end_date,previous2_start_date,previous2_end_date = set_consultation_dates(year)
      model_types = nil
      if options[:format_options].present?
        model_types = Hash.new
        options[:format_options].each do |key,value|
          model_types["#{value[:format_type]}"] = value[:option_select]
        end
      end
      items = self.items_consultation_by(model_types)
      cost_centers = self.cost_centers_consultation_by(model_types)
      if items.present?
        actual_year_results = sql_consultation_report(items,actual_start_date,actual_end_date,cost_centers)
        previous_year_results = sql_consultation_report(items,previous_start_date,previous_end_date,cost_centers)
        previous2_year_results = sql_consultation_report(items,previous2_start_date,previous2_end_date,cost_centers)
        results = self.create_chart_data(actual_year_results,previous_year_results,previous2_year_results)
        return OpenStruct.new(current_year_results:results,previous_year_results:previous_year_results,previous2_year_results:previous2_year_results)
      end
    end



    def self.create_chart_data(results,previous_year_results,previous2_year_results)
      resultado = []
      results.each_with_index do |result,index|
        #each month budget and transaction verify
        january_budget,january_transaction = result['january_budget'].present? ? result['january_budget']:0,result['january_transaction'].present? ? result['january_transaction']:0
        february_budget,february_transaction = result['february_budget'].present? ? result['february_budget']:0, result['february_transaction'].present? ? result['february_transaction']:0
        march_budget,march_transaction= result['march_budget'].present? ? result['march_budget']:0,result['march_transaction'].present? ? result['march_transaction']:0
        april_budget,april_transaction = result['april_budget'].present? ? result['april_budget']:0,result['april_transaction'].present? ? result['april_transaction']:0
        may_budget,may_transaction= result['may_budget'].present? ? result['may_budget']:0,result['may_transaction'].present? ? result['may_transaction']:0
        june_budget,june_transaction = result['june_budget'].present? ? result['june_budget']:0,result['june_transaction'].present? ? result['june_transaction']:0
        july_budget,july_transaction = result['july_budget'].present? ? result['july_budget']:0,result['july_transaction'].present? ? result['july_transaction']:0

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def control
    @month = control_report_params[:month_report].to_i
    @year = control_report_params[:year_report].to_i
    @control_report_detail = Report.control(control_report_params)
    @alpha_month = I18n.l(DateTime.parse(Date::MONTHNAMES[@month]), format: "%B").capitalize
    @total_planification = nil #Only != to nil when rendering from planification

    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def consultation
    @year = consultation_report_params[:year_report]
    @consultation_report_options = consultation_report_params[:format_options]
    @consultation_report_detail = Report.consultation(consultation_report_params)


    respond_to do |format|
      format.html
      format.js{}
    end
  end
  def detailed_control
    @start_year = control_report_params[:start_year].to_i
    @end_year = control_report_params[:end_year].to_i

    @detailed_control_data = Report.detailed_control_report(detailed_report_params)
    respond_to do |format|
      format.html
      format.js{}
    end
  end

  def year_report
    @year = consultation_report_params[:year_report]
    @consultation_report_options = consultation_report_params[:format_options]
    @consultation_report_detail = Report.consultation(consultation_report_params)
    @item_index = consultation_report_params[:item_index]

    respond_to do |format|
      format.html
      format.js{}
    end
  end

  def month_report
    @year = consultation_report_params[:year_report]
    @consultation_report_options = consultation_report_params[:format_options]
    @consultation_report_detail = Report.consultation(consultation_report_params)
    @item_index = consultation_report_params[:item_index]
    @item_month = consultation_report_params[:item_month]
    respond_to do |format|
      format.html
      format.js{}
    end
  end


  private
  def consultation_report_params
    if params[:format_options].present? and params[:year_report].present?
      params.permit({format_options: [:format_type,:option_select]},:year_report,:item_index,:item_month)
    else
      {format_options:nil, year_report:DateTime.now.year}
    end
  end

  def control_report_params
    if params[:month_report].present? and params[:year_report].present?
      params.permit(:month_report,:year_report,:report_type)
    else
       {month_report:DateTime.now.month,year_report:DateTime.now.year,report_type: nil}
    end
  end
  
  def detailed_report_params
    if params[:start_year].present? and params[:end_year].present?
      params.permit(:start_year,:end_year,:report_type)

    else
      current_year = DateTime.now.year
      {start_year:current_year,end_year:current_year,report_type: nil}
    end
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
  
  def get_item_info(item_code)
    Item.search_existence(item_code)
  end
end

app/views/reports/_adjustment_resume.html.haml
-year_adjustment_result.each_with_index do |year_result,index|
  -# year results
  -current_year_adjustment_results = year_result['current_adjustment_results'].present? ? year_result['current_adjustment_results']:0
  -current_year_estimates_results = year_result['current_estimates_results'].present? ? year_result['current_estimates_results']:0
  -previous_year_adjustment_results = year_result['previous_adjustment_results'].present? ? year_result['previous_adjustment_results']:0
  -# month results
  -month_current_year_adjustment_results = month_adjustment_result[index]['current_adjustment_results'].present? ? month_adjustment_result[index]['current_adjustment_results']:0
  -month_current_year_estimate_results = month_adjustment_result[index]['current_estimates_results'].present? ? month_adjustment_result[index]['current_estimates_results']:0
  -previous_month_adjustment_results = month_adjustment_result[index]['previous_adjustment_results'].present? ? month_adjustment_result[index]['previous_adjustment_results']:0
  -# past month result
  -past_month_adjustment_result = month_adjustment_result[index]['current_adjustment_results'].present? ? month_adjustment_result[index]['current_adjustment_results']:0
  -past_month_estimate_result = month_adjustment_result[index]['current_estimates_results'].present? ? month_adjustment_result[index]['current_estimates_results']:0
  -if year_result['adjustment_type'] == ('Indirecto' || 'indirecto')
    %tr
      //Yearly Information
      %td= year_result['concept']
      %td= currency_format(current_year_adjustment_results)
      %td= currency_format(current_year_estimates_results)
      %td= currency_format(previous_year_adjustment_results)
      %td= difference_format(current_year_adjustment_results,previous_year_adjustment_results)
      %td= percentage(current_year_adjustment_results,current_year_estimates_results)
      %td= difference_format(current_year_adjustment_results,previous_year_adjustment_results)
      %td= percentage(current_year_adjustment_results-previous_year_adjustment_results,previous_year_adjustment_results)
      -# //Monthly Information
      %td= currency_format(month_current_year_adjustment_results)
      %td= currency_format(month_current_year_estimate_results)
      %td= currency_format(previous_month_adjustment_results)
      %td= difference_format(month_current_year_estimate_results,month_current_year_adjustment_results)
      %td= percentage(month_current_year_adjustment_results,month_current_year_estimate_results)
      %td= difference_format(month_current_year_adjustment_results,previous_month_adjustment_results)
      %td= percentage((month_current_year_adjustment_results- previous_month_adjustment_results) ,previous_month_adjustment_results)
      -# //Previous Month Information
      %td= currency_format(past_month_adjustment_result)
      %td= difference_format(month_current_year_adjustment_results,past_month_adjustment_result)
      %td= percentage(month_current_year_adjustment_results-past_month_adjustment_result,past_month_adjustment_result)
  -else
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th.text-center{rowspan:1}
              Directos
            %th.danger.text-center
              Gasto Año Actual
            %th.success.text-center
              Presupuesto Año Actual
            %th.danger.text-center
              Gasto Año Anterior
            %th.text-center
              Diferencia
            %th.text-center
              Cump Pptt %
            %th.text-center
              Variación Año Anterior ($)
            %th.text-center
              Variación Año Anterior (%)
            %th.danger.text-center
              Gasto Mes Actual
            %th.success.text-center
              Presupuesto Mes Actual
            %th.danger.text-center
              Gasto Mes Año Anterior
            %th.text-center
              Diferencia
            %th.text-center
              Cump Pptt %
            %th.text-center
              Variación Año Anterior ($)
            %th.text-center
              Variación Año Anterior (%)
            %th.text-center
              Gasto
            %th.text-center
              Variación($)
            %th.text-center
              Variación(%)

        %tbody
          %tr
            //Yearly Information
            %td= year_result['concept']
            %td= currency_format(current_year_adjustment_results)
            %td= currency_format(current_year_estimates_results)
            %td= currency_format(previous_year_adjustment_results)
            %td= difference_format(current_year_adjustment_results,previous_year_adjustment_results)
            %td= percentage(current_year_adjustment_results,current_year_estimates_results)
            %td= difference_format(current_year_adjustment_results,previous_year_adjustment_results)
            %td= percentage(current_year_adjustment_results-previous_year_adjustment_results,previous_year_adjustment_results)
            -# //Monthly Information
            %td= currency_format(month_current_year_adjustment_results)
            %td= currency_format(month_current_year_estimate_results)
            %td= currency_format(previous_month_adjustment_results)
            %td= difference_format(month_current_year_estimate_results,month_current_year_adjustment_results)
            %td= percentage(month_current_year_adjustment_results,month_current_year_estimate_results)
            %td= difference_format(month_current_year_adjustment_results,previous_month_adjustment_results)
            %td= percentage((month_current_year_adjustment_results- previous_month_adjustment_results) ,previous_month_adjustment_results)
            -# //Previous Month Information
            %td= currency_format(past_month_adjustment_result)
            %td= difference_format(month_current_year_adjustment_results,past_month_adjustment_result)
            %td= percentage(month_current_year_adjustment_results-past_month_adjustment_result,past_month_adjustment_result)

app/views/reports/_card_details.html.haml
.col-md-2
  .card.card-stats
    .card-content{"data-background-color"=> "blue"}
      %p.category.text-center
        %i.fa{:class => icon_option}
        = title
      %h4.title.text-center
        = value

app/views/reports/_detail.html.haml
.page-header
  %h1
    Detalle de Reporte Control
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th.text-center{rowspan:2}
          Año
        %th.text-center{rowspan:2}
          Concepto
        %th.danger.text-center{colspan:12}
          Gasto
        %th.success.text-center{colspan:12}
          Presupuesto
      %tr
        %th.text-center
          Enero
        %th.text-center
          Febrero
        %th.text-center
          Marzo
        %th.text-center
          Abril
        %th.text-center
          Mayo
        %th.text-center
          Junio
        %th.text-center
          Julio
        %th.text-center
          Agosto
        %th.text-center
          Septiembre
        %th.text-center
          Octubre
        %th.text-center
          Noviembre
        %th.text-center
          Diciembre
        %th.text-center
          Enero
        %th.text-center
          Febrero
        %th.text-center
          Marzo
        %th.text-center
          Abril
        %th.text-center
          Mayo
        %th.text-center
          Junio
        %th.text-center
          Julio
        %th.text-center
          Agosto
        %th.text-center
          Septiembre
        %th.text-center
          Octubre
        %th.text-center
          Noviembre
        %th.text-center
          Diciembre
    %tbody
      - detail_data.each_with_index do |detail,index|
        %tr
          %td
            =detail['year'].to_i
          %td
            = detail['concept']
          -(1..12).each do |month|
            %td
              = currency_format(detail["#{get_month(month,true)}_transaction"].to_i)


          -(1..12).each do |month|
            %td
              = currency_format(detail["#{get_month(month,true)}_budget"].to_i)

app/views/reports/_kpi_details.html.haml
.col-md-3
  .card.card-stats
    .card-header{"data-background-color"=> "orange", "data-toggle" => "tooltip", :title => tooltip_content}
      %i.fa{:class => icon_option}
    .card-content
      %p.category
        = category
      %h3.title
        =title
    .card-footer
      .stats
        %p= footer
:javascript
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
  });

app/views/reports/consultation.html.haml
.row
  %h1.col-md-offset-1 Periodo de Análisis
  = form_tag reports_consultation_path, method: :get, class:'form-horizontal',remote: true do
    .form-group
      %h4.control-label.col-md-1{:for => "year_report"} Año:
      .col-md-2
        = select_tag 'year_consultation_report', options_for_select(Report.years_availables,DateTime.now.year)
      .col-md-4
        = submit_tag "Generar Reporte", class:'btn btn-info', id: 'consultation_commit'

.row
  %h1.col-md-offset-1
    Filtros Item
.row
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categorySpainSelect"} Categoria España:
    .col-md-2
      = select_tag 'Categoria España', options_for_select(FormatSpain.names_availables),class: "consultation_select", id:"#{get_report_type('format_spain')}",:include_blank=>true
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categoryBankSelect"} Categoria Banca:
    .col-md-2
      = select_tag 'Categoria Banca', options_for_select(FormatBank.names_availables),class: "consultation_select", id:"#{get_report_type('format_bank')}",:include_blank=>true
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categoryGroupSelect"} Categoria Grupo:
    .col-md-2
      = select_tag 'Categoria Grupo', options_for_select(FormatGroup.names_availables),class: "consultation_select", id:"#{get_report_type('format_group')}",:include_blank=>true
.row
  .form-group.col-sm-4
    %label.control-label.col-sm-6{:for => "categoryCargabalSelect"} Categoria Cargabal:
    .col-md-2
      = select_tag 'Categoria Cargabal', options_for_select(InterpretationCargabal.names_availables),class: "consultation_select", id:"#{get_report_type('format_cargabal')}",:include_blank=>true
  .form-group.col-sm-4
    %label.control-label.col-sm-6{:for => "categoryCccSelect"} Categoria CCC:
    .col-md-2
      = select_tag 'Categoria CCC', options_for_select(InterpretationCcc.names_availables), class: "consultation_select",id:"#{get_report_type('format_ccc')}",:include_blank=>true
  .form-group.col-sm-4
    %label.control-label.col-sm-6{:for => "categoryGeSelect"} Categoria GES:
    .col-md-2
      = select_tag 'Categoria GES', options_for_select(InterpretationGe.names_availables), class: "consultation_select",id:"#{get_report_type('local_gp')}",:include_blank=>true
.row
  .form-group.col-sm-4
    %label.control-label.col-sm-6{:for => "categorySubfieldSelect"} Categoria Subcampo:
    .col-md-2
      = select_tag 'Categoria Subcampo', options_for_select(Subfield.names_availables), class: "consultation_select",id:"#{get_report_type('format_subfield')}",:include_blank=>true
.row
  %h1.col-md-offset-1
    Filtros Centro de costos
.row
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categoryDivisionSelect"} División:
    .col-md-2
      = select_tag 'División', options_for_select(CostCenter.division_availables),class: "consultation_select", id:"#{get_report_type('division')}",:include_blank=>true
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categoryManagementSelect"} Gerencia:
    .col-md-2
      = select_tag 'Gerencia', options_for_select(CostCenter.management_availables),class: "consultation_select", id:"#{get_report_type('management')}",:include_blank=>true
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categoryAreaSelect"} Área:
    .col-md-2
      = select_tag 'Área', options_for_select(CostCenter.area_availables),class: "consultation_select", id:"#{get_report_type('area')}",:include_blank=>true
  .form-group.col-md-4
    %label.control-label.col-sm-6{:for => "categorySubareaSelect"} Subárea:
    .col-md-2
      = select_tag 'Subárea', options_for_select(CostCenter.subarea_availables),class: "consultation_select", id:"#{get_report_type('subarea')}",:include_blank=>true
%h1.page-header.col-md-offset-1
  Reporte de Consulta


#resume-consultation-report
  =render partial: 'consultation_resume', locals: {year: @year, consultation_report_detail: @consultation_report_detail}

app/views/reports/control.html.haml
.row
  .col-md-6
    %h1 Periodo de Análisis
    = form_tag reports_control_path, method: :get, class:'form-horizontal',remote: true do
      .form-group
        %label.control-label.col-sm-2{:for => "year_report"} Año:
        .col-sm-10
          = select_tag 'year_report', options_for_select(Report.years_availables,DateTime.now.year)
      .form-group
        %label.control-label.col-sm-2{:for => "month"} Mes:
        .col-sm-10
          = select_tag 'month_report', options_for_select(options_months,DateTime.now.month)

      .form-group
        .col-sm-offset-2.col-sm-10
          = submit_tag "Total", class:'btn btn-info'
  .col-md-6
    %h1
      Filtros
    %br
    %br
    .btn-group{:role => "group"}
      = link_to 'Categoria España', '#',class:'btn btn-info', id:'format_spain',data: {'report-type' => get_report_type('format_spain')}
      = link_to 'Categoria Local GP', '#',class:'btn btn-info',data: {'report-type' => get_report_type('local_gp')}
      = link_to 'Categoria CCC', '#',class:'btn btn-info',data: {'report-type' => get_report_type('format_ccc')}

.page-header
  %h1
    Reporte de Control

#resume-control-report
  =render partial: 'control_resume', locals: {alpha_month: @alpha_month, year: @year, control_report_detail: @control_report_detail,total_planification:@total_planification}

app/views/reports/detailed_control.html.haml
.row.col-md-5
  .col-md-12
    %h1 Periodo de Análisis
    = form_tag reports_detailed_control_path, method: :get, class:'form-horizontal',remote: true do
      .form-group
        %label.control-label.col-md-4{:for => "start_year"} Año Inicio:
        .col-md-2
          = select_tag 'start_year', options_for_select(Report.years_availables,DateTime.now.year)
      .form-group
        %label.control-label.col-md-4{:for => "end_year"} Año Termino:
        .col-md-2
          = select_tag 'end_year', options_for_select(Report.years_availables,DateTime.now.year)

      .form-group
        .col-md-10
          = submit_tag "Generar Reporte", class:'btn btn-info'
.row.col-md-7
  .col-md-12
    %h1
      Filtros
  .col-md-12
    %label
  .col-md-12
    .btn-group{:role => "group"}
      = link_to 'Detalle Categoria España', '#',class:'btn btn-success',data: {'detailed-report-type' => get_report_type('format_spain')}
    .btn-group{:role => "group"}
      = link_to 'Detalle Categoria Local GP', '#',class:'btn btn-success',data: {'detailed-report-type' => get_report_type('local_gp')}
    .btn-group{:role => "group"}
      = link_to 'Detalle Categoria CCC', '#',class:'btn btn-success',data: {'detailed-report-type' => get_report_type('format_ccc')}

.row
  .col-md-12
    #detail-control-report
      =render partial: 'detail', locals: {start_year:@start_year,end_year: @end_year, detail_data: @detailed_control_data}